server.servlet.context-path = /FlashG
spring.application.name= FlashG

# BD
spring.datasource.url=jdbc:postgresql://localhost:5432/FlashG
spring.datasource.username=postgres
spring.datasource.password=ifpb


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.encoding=UTF-8
spring.jpa.show-sql=false

# server
server.port=8080

# Desativa a página padrão de erro do Spring Boot
server.error.whitelabel.enabled=false

# Define o caminho para o controlador de erro
server.error.path=/error
